# Generated by Django 3.1.6 on 2021-02-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentFTE', models.DecimalField(decimal_places=2, max_digits=3)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fteform.faculty')),
            ],
        ),
    ]
