# Generated by Django 3.1.6 on 2021-02-03 16:19

from django.db import migrations, models
import django.db.models.deletion
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('fteform', '0003_faculty_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='active',
        ),
        migrations.AddField(
            model_name='fte',
            name='effectiveFrom',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fte',
            name='effectiveTo',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fte',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte', to='fteform.faculty'),
        ),
    ]
